KhronosGroup/Vulkan-Headers

- include/vulkan/vk_icd.h
Change allow us to refer to ANativeWindow from C code, fixes following
compilation error seen with clang 3.8.27580 (Android O prebuilts).
vk_icd.h:116:5: error: must use 'struct' tag to refer to type 'ANativeWindow'
Signed-off-by: Tapani Pälli <tapani.palli@intel.com>
> headers: fix compilation error on android with vk_icd.h

- include/vulkan/vk_layer.h
The header `vk_layer.h` included `vk_layer_dispatch_table.h`, which is not present in this repo. Instead, it had to be generated from either the Vulkan-Loader or Vulkan-ValidationLayers repo. This change removes that dependency.
Note that merging this change right now will break the Vulkan-Loader and Vulkan-ValidationLayer repos as they use the contents of `vk_layer_dispatch_table.h` in a few places, while only including `vk_layer.h`. I will open pull requests in those repos shortly that address this problem and I'll link to them from this PR once I do.
Update: The PRs that this depends on are:
- KhronosGroup/Vulkan-Loader#48
- KhronosGroup/Vulkan-ValidationLayers#225
> headers: Remove loader/layer dependency

- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_fuchsia.h
- registry/genvk.py
- registry/reg.py
- registry/validusage.json
- registry/vk.xml
Updated:
- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/genvk.py
- registry/reg.py
- registry/validusage.json
- registry/vk.xml
Added:
- include/vulkan/vulkan_fuchsia.h
Note: A local, modified version of Vulkan-Docs/xml/reg.py was used to
generate these files. This modification filters out disabled extensions
when populating the structextends list for a given base struct.
> headers: Update to Vulkan header version 1.1.87

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
This header update includes a correction to enum value `VK_STRUCTURE_TYPE_IMAGE_EXCPLICIT_DRM_FORMAT_MODIFIER_CREATE_INFO_EXT` which exists in an [MR](https://gitlab.khronos.org/vulkan/vulkan/merge_requests/2873) and has been approved to be merged but has not been merged yet. 
Updated:
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.89

- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_android.h
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_fuchsia.h
- include/vulkan/vulkan_ios.h
- include/vulkan/vulkan_macos.h
- include/vulkan/vulkan_vi.h
- include/vulkan/vulkan_wayland.h
- include/vulkan/vulkan_win32.h
- include/vulkan/vulkan_xcb.h
- include/vulkan/vulkan_xlib.h
- include/vulkan/vulkan_xlib_xrandr.h
- registry/cgenerator.py
- registry/generator.py
- registry/genvk.py
- registry/reg.py
- registry/validusage.json
- registry/vk.xml
Updated:
- `include/vulkan/vulkan.h`
- `include/vulkan/vulkan_android.h`
- `include/vulkan/vulkan_fuchsia.h`
- `include/vulkan/vulkan_ios.h`
- `include/vulkan/vulkan_macos.h`
- `include/vulkan/vulkan_vi.h`
- `include/vulkan/vulkan_wayland.h`
- `include/vulkan/vulkan_win32.h`
- `include/vulkan/vulkan_xcb.h`
- `include/vulkan/vulkan_xlib.h`
- `include/vulkan/vulkan_xlib_xrandr.h`
- `registry/cgenerator.py`
- `registry/generator.py`
- `registry/genvk.py`
- `registry/reg.py`
> headers: Update to Vulkan header version 1.1.97

- BUILD.gn
Step one of adding GN build support.  The common definitions here will be used by Vulkan-ValidationLayers, Vulkan-Loader, and Vulkan-Tools
> Add support for GN build system

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/conventions.py
- registry/validusage.json
- registry/vk.xml
This updates the C headers to tag v1.1.108 from the Vulkan-Docs repo, but there's another build issue with VulkanHppGenerator:
> % (cd build && ./VulkanHppGenerator)
> Loading vk.xml from /home/tree/git/Vulkan-Hpp/Vulkan-Docs/xml/vk.xml
> Writing vulkan.hpp to /home/tree/git/Vulkan-Hpp/vulkan/vulkan.hpp
> warning: Unknown element in spec on line: 8093 comment!
> VulkanHppGenerator: /home/tree/git/Vulkan-Hpp/VulkanHppGenerator.cpp:1463: void VulkanHppGenerator::readExtensionDisabledRequire(const tinyxml2::XMLElement*): Assertion `value == "enum"' failed.
> Abort
I opened https://github.com/KhronosGroup/Vulkan-Hpp/issues/329 to get this resolved.
> Update for Vulkan-Docs 1.1.108 - needs fix for VulkanHppGenerator

- include/vulkan/vk_icd.h
In order to properly support the `VK_EXT_metal_surface` extension, the loader needs a metal surface structure in `vk_icd.h`. This PR adds that structure.
> Add metal surface support to ICD header

- BUILD.gn
BUILD.gn does not define VK_USE_PLATFORM_MACOS_MVK for MacOS
> build: BUILD.gn missing defines for MacOS

- BUILD.gn
This is conditional upon defining a variable 'is_ggp'. The variable is
optional.
@mikes-lunarg or @oddhack PTAL
> GN: Add support for Google Games Platform.

- BUILD.md
It was not specified that the windows commands must be run from within a developer console.
Also removed VS2013 and added VS2019 refs.
Would have helped with #92.
> build: Clarify Windows build instructions

- BUILD.gn
Not all Linux platforms will have X11 available (Wayland, GGP), so we have to declare a variable that checks use_x11 separately.
This depends on an ANGLE bug: https://bugs.chromium.org/p/angleproject/issues/detail?id=4116
> GN: Make PLATFORM_XCB optional, based on a user-defined variable.

- include/vulkan/vk_icd.h
Add VI enum value to VkIcdWsiPlatform and define type VkIcdSurfaceVi.
> Add VI WSI platform support to vk_icd.h

- include/vulkan/vk_icd.h
Defines type "VkIcdSurfaceGgp" and adds "VK_ICD_WSI_PLATFORM_GGP" to
VkIcdWsiPlatform enum.
GGP is Google Games Platform, the platform for Stadia.
> Add GGP (Stadia) WSI platform support to vk_icd.h

- include/vulkan/vk_icd.h
Hi,
This PR adds support for QNX Screen platform to the ICD header.
Not sure about patch for the genvk.py script, according to docs Vulkan-Docs should have the reference one, but it appears that this repository has more recent and updated genvk.py script. Same patch was already merged into the Vulkan-Docs.
Thanks!
> Add support for QNX Screen platform to ICD header.

- CMakeLists.txt
This lets downstream repos that use `VULKAN_HEADERS_INSTALL_DIR` for headers find the new files
> Add vk_video headers to CMake install target

- include/vulkan/vulkan_beta.h
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- registry/vkconventions.py
This should fix a problem reported with the definition of VK_NULL_HANDLE in 1.2.175 for certain versions of MSVC.
> Update for Vulkan-Docs 1.2.176

- include/vulkan/vulkan_funcs.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
Notably includes fix for https://github.com/KhronosGroup/Vulkan-Hpp/issues/1167 which is blocking downstream CI systems
> Update to latest Vulkan-Hpp

- include/vk_video/vulkan_video_codec_h265std_encode.h
Release procedure needed a tweak to always copy vk_video/* to this repo.
> Add missing update for vk_video headers

- BUILD.gn
Wayland headers can be found in multiple directories.
Here we use the array `vulkan_wayland_include_dirs` to specify those include directories.
This is an improvement of https://github.com/KhronosGroup/Vulkan-Headers/pull/267.
Also related to [this chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/3455146/comments/c1dba934_3a7f5e43).
@null77 @mikes-lunarg
> GN: Wayland include directories

- BUILD.md
- CMakeLists.txt
- README.md
- include/vulkan/vk_icd.h
- include/vulkan/vk_layer.h
- video headers don't exist on this branch (and are not supported for Vulkan SC)
- loader interface files need to use vulkansc include instead of vulkan
- update documentation
> Fix build for downstream VulkanSC uses

- README.md
Noticed this file had moved but hadn't been reflected in the readme
> Fix the readme for the fixed conventions.py location

- CMakeLists.txt
Currently GNUInstallDirs is complaining because no language has been enabled. This is fixed by enabling the C language.
Here is the full error:
```
CMake Warning (dev) at /home/juan/projects/dk/cmake/share/cmake-3.24/Modules/GNUInstallDirs.cmake:243 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
Call Stack (most recent call first):
CMakeLists.txt:29 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> build: Fix CMake warning

- CMakeLists.txt
- cmake/version.cmake
Extract the vulkan header version for CMake usage
This partially address the concerns highlighted by https://github.com/KhronosGroup/Vulkan-Headers/pull/207 by getting the version string.
Example output from cmake generation:
```
-- The C compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Vulkan-Headers = 1.3.233
-- Configuring done
-- Generating done
```
> cmake: Get Vulkan Version

- include/vulkan/vk_sdk_platform.h
`vk_platform_sdk.h` left this definition unguarded, potentially causing problems where this symbol is defined globally.
> Guard against multiple NOMINMAX definitions

- BUILD.md
- CMakeLists.txt
- cmake/install.cmake
Now as part of install 2 files are created:
- VulkanHeadersConfig.cmake
- VulkanHeadersConfigVersion.cmake
This allows usage of find_package
closes #157
Also closes https://github.com/KhronosGroup/Vulkan-Headers/pull/207
> cmake: Export CMake Targets File

- include/vulkan/vk_icd.h
This allows the loader to implement its part of the VK_FUCHSIA_image_pipe extension.
> Add VkIcdSurfaceImagePipe and VK_ICD_WSI_PLATFORM_FUCHSIA

- cmake/install.cmake
Currently the include directory is arch-dependent. However, the location where the *.cmake files are installed
is arch-independent. This difference causes an issue with cross compile environments.
> cmake: Fix environment for cross-compile installs

- cmake/install.cmake
We need to revert b092b2f in Gentoo to fix multi-ABI vulkan-loader build
This reverts commit b092b2fccc812453c1d0ec0a829eb8f34f174803.
See https://github.com/KhronosGroup/Vulkan-Headers/issues/330 for details.
> cmake: Fix cross-compilation

- include/vulkan/vk_icd.h
If an ICD supports any of the following functions, they must be queryable with vk_icdGetInstanceProcAddr:
vk_icdNegotiateLoaderICDInterfaceVersion
vk_icdGetPhysicalDeviceProcAddr
vk_icdEnumerateAdapterPhysicalDevices (Windows only)
In addition, these functions no longer need to be exported directly.
These changes allow drivers to no longer export the 'loader-icd interface' functions which previously had to be exported. This change aids in future extension work which aims to provide the ability to load drivers without installing them to the system.
> vk_icd.h: Add ICD Version 7

- CMakeLists.txt
Partially addresses https://github.com/KhronosGroup/Vulkan-Headers/issues/336
Permissions are now preserved for genvk.py
> cmake: Preserve permissions from registry files

- include/vulkan/vk_layer.h
vulkan.h pulls in system headers we don't need
closes #313
> vk_layer: Include vukan_core.h instead of vulkan.h

- BUILD.md
- CMakeLists.txt
- README.md
- cmake/VulkanHeadersConfig.cmake.in
Vulkan::Registry behaves differently in `add_subdirectory` vs
`find_package` builds. Which can result in build failures.
Also Vulkan::Registry never made sense as a CMake target and
was very brittle in numerous ways.
Better to provide a `VULKAN_HEADERS_REGISTRY_DIRECTORY` to users
instead and remove Vulkan::Registry completely.
closes #351
> cmake: Remove Vulkan::Registry

- BUILD.md
- CMakeLists.txt
- use -DVULKANSC=ON instead of -DVulkanSC=TRUE
> Build: Change VULKAN SC CMake option to be consistent with other options

- include/vulkan/vk_layer.h
- tests/vk_layer.c
- It hasn't been handling windows (so it's been half implemented)
- It's a suboptimal method for exporting symbols for vulkan layers since `--version-script` and `.def` files exists. Both of these methods also don't risk name mangling.
- `--version-script` also has perf benefits since you can silence exports from code you didn't intend to export
> headers: Remove VK_LAYER_EXPORT

- BUILD.gn
The SC vk.xml merge added extra parentheses to the VK_DEFINE_NON_DISPATCHABLE_HANDLES macro in order to satisfy MISRA rule 20.7.  Make sure this doesn't break downstream builds that would otherwise warn about them.
> Add -Wno-redundant-parens to BUILD.gn

- .github/workflows/linux.yml
- CMakeLists.txt
- Removes conditional 3.15 logic
- Guarantees usage of --install/--loglevel for CI/package managers
> cmake: Update min to 3.15

- registry/generator.py
- registry/genvk.py
- registry/reg.py
- registry/vk.xml
> Update for Vulkan-Docs 1.3.248

- .github/workflows/linux.yml
Closes #399 
contents: read is enough for linux.yml to run, see https://github.com/joycebrum/Vulkan-Headers/actions/runs/4985111418
> Set minimal permissions to github workflows

- README.md
This is intended to clarify that developers using Vulkan are likely to need only the header files, not the scripts and other material in the repository which are used by the SDK and other downstream ecosystem components.
Closes #407
> Update README to be more clear about use of the different files in the repo

- CMakeLists.txt
- tests/add_subdirectory/CMakeLists.txt
VULKAN_HEADERS_INSTALL was added since it was believed there was a valid use case for it.
After looking into the use case that provoked this change there is no reason to keep VULKAN_HEADERS_INSTALL as an option.
Here is the use case we do NOT want to support:
https://github.com/KhronosGroup/Vulkan-Headers/pull/416#issuecomment-1622318949
Fundamentally this problem is caused add_subdirectory/find_package not being able to work together flawlessly.
Which isn't the responsibility of Vulkan-Headers to fix.
It's the responsibility of projects that consume Vulkan-Headers to account for either method.
> cmake: Remove VULKAN_HEADERS_INSTALL

- CMakeLists.txt
See the following discussion for context:
https://discourse.cmake.org/t/what-should-the-destination-be-for-a-header-only-librarys-cmake-config-file/8473/3
TLDR: `DATADIR` can be `share` but it doesn't have to be. It can be changed by the user.
> cmake: Use share instead of DATADIR for CMake config files

- tests/CMakeLists.txt
- tests/vk_icd.c
- tests/vk_layer.c
> ci: Fix -Wdeprecated-non-prototype warnings

- .github/workflows/ci.yml
https://github.com/orgs/community/discussions/26276
> ci: Prevent duplicate CI runs

- .github/workflows/ci.yml
Well the prior change does eliminate duplicate runs it stops automated testing on forks.
> ci: Fix fork development

- BUILD.gn
closes KhronosGroup/Vulkan-ValidationLayers/issues/6780
> gn: Fix validation layer build

- .github/workflows/ci.yml
- tests/CMakeLists.txt
> Fix testing for 3.15

- BUILD.gn
av1std_decode.h & av1std.h were added recently and needed adding to the build.gn build.
> build: Update build.gn with AV1 headers

- .github/workflows/ci.yml
- CMakeLists.txt
This makes the project more composable: It can be built and tested as part of a larger set of projects, from source.
> cmake: Allow external control of whether to test or install

- .github/workflows/ci.yml
- CMakeLists.txt
- tests/CMakeLists.txt
Added a new `IMPORTED` target and CMake library, `Vulkan::VulkanHppModule` that consumers can link against, to transparently use `import vulkan_hpp;`
- Avoids users having to [set the library up themselves](https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#usage-with-cmake)
- Code mostly derived from [CMake's own tests](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Tests/RunCMake/CXXModules/examples/export-with-headers-install/CMakeLists.txt)
- Guarded this target behind a version test requiring at least CMake version 3.28
> Add a new `IMPORTED` target `Vulkan::VulkanHppModule` which contains `vulkan.cppm`

- Makefile
- Makefile.release
- registry/stripAPI.py
Motivated by recent problems building the SC 1.0.15 spec update - will import to VulkanSC-Headers and tweak once it's proven out for Vulkan-Headers.
The Makefile may need to be modified when directory structure is changed or new scripts or headers are added.
> Makefile to import generated scripts and headers when doing a spec update

- CMakeLists.txt
Can't use `MSVC` var because it is also true for clang-cl. Fixes #500.
> Fix MSVC identification for modules support

- .github/workflows/ci.yml
- CMakeLists.txt
- tests/integration/CMakeLists.txt
Matches Vulkan Validation Layers and SPIRV-Tools.
> cmake: Update minimum version to 3.22.1

- BUILD.gn
This is required to define vkCreateXlibSurfaceKHR, which is required by GTK4.
Depends on Dawn CL:
https://dawn-review.googlesource.com/c/dawn/+/229494
Needed to fix this Chromium issue:
https://g-issues.chromium.org/issues/345261080
> GN build: Define VK_USE_PLATFORM_XLIB_KHR

- CMakeLists.txt
Currently we are installing `.cppm` files even if `VULKAN_HEADERS_ENABLE_MODULE` is off.
Right now in Gentoo we are just manually deleting the files, would be nice to have a clean solution.
Let me know if there's a way to prevent the copy paste here.
> CMake: Don't install C++ module headers if module build is disabled

- CMakeLists.txt
Reverts KhronosGroup/Vulkan-Headers#557
This breaks users who were expecting the module file to be present, such as the SDK. Because installing headers do not know what compiler will use it, we shouldn't prevent it from being installed (AKA copied, not compiled).
> Revert "CMake: Don't install C++ module headers if module build is disabled"
