KhronosGroup/Vulkan-Headers

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- updated vk.xml
- updated vulkan_core.h
- updated validusage.json
- updated vulkan.hpp
> Update to version 1.1.77 of the Vulkan hdr

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- update vk.xml
- update vulkan_core.h
- update validusage.json
- update vulkan.hpp
> Update to version 1.1.79 of the Vulkan header

- README.md
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/vk.xml
This required a change to VVL, already pushed, and is necessary to pull in Alex's 8Bit Storage validation changes from the private repo.
> Update header repo to 1.1.80

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- updated validusage.json
- updated vk.xml
- updated vulkan.hpp
- updated vulkan_core.h
> Update to version 1.1.81 of the Vulkan header 

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- updated validusage.json
- updated vk.xml
- updated vulkan.hpp
- updated vulkan_core.h
> Update to version 1.1.82 of the Vulkan header

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
- updated validusage.json
- updated vk.xml
- updated vulkan.hpp
- updated vulkan_core.h
> headers: Update to Vulkan-Headers version 1.1.84

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
Updated:
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
Note: vulkan.hpp required some hand editing in
Device::getAccelerationStructureHandleNVX and
Device::getRaytracingShaderHandlesNVX in order to compile.
> headers: Update to version 1.1.85

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
Updated:
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.90

- include/vulkan/vulkan.h
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/genvk.py
- registry/validusage.json
- registry/vk.xml
Updated:
- `include/vulkan/vulkan.h`
- `registry/genvk.py`
> headers: Update to Vulkan header version 1.1.91

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.92

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.94

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.95

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.96

- README.md
Added a note to `README.md` about the new version tagging scheme.
Resolves #23
> docs: Add explanation of version tagging scheme

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> headers: Update to Vulkan header version 1.1.101

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
This builds cleanly, so will accept momentarily.
> Update for Vulkan-Docs 1.1.106

- include/vulkan/vk_layer.h
Header changes for https://github.com/KhronosGroup/Vulkan-Loader/issues/74
> headers: device creation callbacks for layers

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
It took several round trips to get Vulkan-Hpp building with Vulkan-Docs updates, so this is the first one since 1.1.108, but we seem to be OK now.
> Update for Vulkan-Docs 1.1.111

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/validusage.json
- registry/vk.xml
> Update for Vulkan-Docs 1.1.112

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- registry/generator.py
- registry/validusage.json
- registry/vk.xml
Vulkan-Hpp does not build, yet.
> Update for Vulkan-Docs 1.1.119

- registry/spec_tools/util.py
> Add new local dependency of scripts.

- README.md
Several files originate from unknown (to @oddhack) sources and that should be fixed before accepting this PR. Assigning to @mark-lunarg to help figure that out.
> Enumerate originating repository for all files in this repo

- include/vulkan/vk_icd.h
This is useful for integration with Vulkan-Loader.
Nicolas Caramelli
> Update vk_icd.h for VK_EXT_directfb_surface extension

- BUILD.gn
Add new vulkan_screen.h header to BUILD.gn
fixes #187
> Fix build after adding new header

- include/vk_video/vulkan_video_codec_h264std.h
- include/vk_video/vulkan_video_codec_h264std_decode.h
- include/vk_video/vulkan_video_codec_h264std_encode.h
- include/vk_video/vulkan_video_codec_h265std.h
- include/vk_video/vulkan_video_codec_h265std_decode.h
- include/vk_video/vulkan_video_codecs_common.h
> Omitted static vk_video/ headers in the 1.2.175 update.

- BUILD.gn
Following the approach taken with XCB, add support for Wayland based on user-defined variable.
> GN: Support Wayland platform

- CMakeLists.txt
> Fix duplicate quotes when targets are included by downstream projects

- .github/workflows/linux.yml
Ensures CMake build passes as intended
> ci: Add GitHub actions

- .github/workflows/linux.yml
- CMakeLists.txt
- README.md
- tests/CMakeLists.txt
- tests/vk_icd.c
- tests/vk_layer.c
- tests/vk_sdk_platform.c
Ensures the non-API headers compile correctly
> tests: Test Non-API headers

- BUILD.md
> docs: Minimal BUILD.md documentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Just specify the list of files to avoid contributor confusion.
> docs: Improve github templates

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_enums.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
- include/vulkan/vulkan_static_assertions.hpp
- include/vulkan/vulkan_to_string.hpp
- registry/vk.xml
> Update for Vulkan-Docs 1.3.240

- README.md
CONTRIBUTING.md, issue template, and PR template all cover this.
> docs: Trim README.md

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_enums.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
- include/vulkan/vulkan_static_assertions.hpp
- include/vulkan/vulkan_to_string.hpp
- registry/vk.xml
> Update for Vulkan-Docs 1.3.245

- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
vulkan_core.h was not updated for some reason.
> Update for Vulkan-Docs 1.3.248

- CONTRIBUTING.md
> Add new .cppm file to CONTRIBUTING.md

- .github/workflows/linux.yml
- CMakeLists.txt
- tests/add_subdirectory/CMakeLists.txt
Allows add_subdirectory users to install vulkan-headers
> cmake: Add VULKAN_HEADERS_INSTALL option

- .reuse/dep5
- include/vulkan/vulkan.cppm
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_enums.hpp
- include/vulkan/vulkan_extension_inspection.hpp
- include/vulkan/vulkan_funcs.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
- include/vulkan/vulkan_raii.hpp
- include/vulkan/vulkan_shared.hpp
- include/vulkan/vulkan_static_assertions.hpp
- include/vulkan/vulkan_to_string.hpp
- registry/profiles/VP_KHR_roadmap.json
- registry/vk.xml
Note that `registry/profiles/VP_KHR_roadmap.json` was renamed from `registry/profiles/VP_KHR_roadmap_2022.json`, now that the file contains multiple roadmap profiles.
> Update for Vulkan-Docs 1.3.276

- include/vulkan/vulkan.cppm
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_enums.hpp
- include/vulkan/vulkan_extension_inspection.hpp
- include/vulkan/vulkan_funcs.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
- include/vulkan/vulkan_shared.hpp
- include/vulkan/vulkan_static_assertions.hpp
- include/vulkan/vulkan_to_string.hpp
- registry/vk.xml
> Update for Vulkan-Docs 1.3.293

- include/vulkan/vulkan.cppm
- include/vulkan/vulkan.hpp
- include/vulkan/vulkan_core.h
- include/vulkan/vulkan_enums.hpp
- include/vulkan/vulkan_extension_inspection.hpp
- include/vulkan/vulkan_funcs.hpp
- include/vulkan/vulkan_handles.hpp
- include/vulkan/vulkan_hash.hpp
- include/vulkan/vulkan_raii.hpp
- include/vulkan/vulkan_shared.hpp
- include/vulkan/vulkan_static_assertions.hpp
- include/vulkan/vulkan_to_string.hpp
- registry/vk.xml
> Update for Vulkan-Docs 1.3.294
